Document: multiforcer
Title: Debian multiforcer Manual
Author: <insert document author here>
Abstract: This manual describes what multiforcer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/multiforcer/multiforcer.sgml.gz

Format: postscript
Files: /usr/share/doc/multiforcer/multiforcer.ps.gz

Format: text
Files: /usr/share/doc/multiforcer/multiforcer.text.gz

Format: HTML
Index: /usr/share/doc/multiforcer/html/index.html
Files: /usr/share/doc/multiforcer/html/*.html
